"""Project model updated

Revision ID: 56d367e9cdf8
Revises: e496660080a5
Create Date: 2025-12-01 20:15:21.588913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56d367e9cdf8'
down_revision: Union[str, Sequence[str], None] = 'e496660080a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sandbox_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_sandbox_id'), 'projects', ['sandbox_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_sandbox_id'), table_name='projects')
    op.drop_column('projects', 'sandbox_id')
    # ### end Alembic commands ###
